theme: jekyll-theme-dinky
title: Day In The Life - Agile Integration
description: The agile integration with APIs and containers event is a hands-on workshop for developing, testing, and deploying cloud-native, integrated solutions. This full-day workshop will start with an overview of agile integration and a discussion of the necessary architecture.
show_downloads: true
